site_name: TokaMap

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    - scheme: default
      primary: white
      accent: light blue
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share

nav:
  - Home: index.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - mkdocstrings
  - mike

extra:
  version:
    provider: mike
    default: latest
